# Generated by Django 6.0.4 on 2026-05-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ai_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
